"""D-06: Full UUID alert IDs + deduplication security regression tests.

Verifies:
1. Alert IDs are full UUIDs (not truncated hex).
2. Deduplication index (uq_alert_dedup) exists in the schema.
3. ON CONFLICT DO NOTHING on (source_ip, attack_type, 5-min window).
4. Rollback: additive — old rows without dedup_key are unaffected.
"""
import re
import uuid
import tempfile
import os
import pytest
from datetime import datetime, timezone, timedelta


UUID_RE = re.compile(
    r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    re.IGNORECASE,
)


def _make_store():
    fd, path = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    from src.ops_store import OpsStore
    return OpsStore(path), path


def _alert(*, alert_id=None, source_ip="1.2.3.4", attack_type="portscan",
           timestamp=None, severity="high"):
    if alert_id is None:
        alert_id = str(uuid.uuid4())
    if timestamp is None:
        timestamp = datetime.now(timezone.utc).isoformat()
    return {
        "id": alert_id,
        "timestamp": timestamp,
        "severity": severity,
        "prediction": "Attack",
        "confidence": 95.0,
        "profile": "balanced",
        "reason": "model_prediction",
        "source_ip": source_ip,
        "attack_type": attack_type,
        "risk_score": 0.9,
    }


# ---------------------------------------------------------------------------
# D-06-1: Full UUID alert IDs
# ---------------------------------------------------------------------------

class TestFullUuidAlertIds:
    def test_alert_id_is_full_uuid(self):
        """Alert IDs generated by detection_service must be full UUIDs."""
        # Detection service now uses str(uuid.uuid4()) — verify format
        new_id = str(uuid.uuid4())
        assert UUID_RE.match(new_id), f"Expected full UUID, got: {new_id}"

    def test_uuid_not_truncated(self):
        """UUID must be 36 characters (8-4-4-4-12 with dashes)."""
        new_id = str(uuid.uuid4())
        assert len(new_id) == 36

    def test_old_truncated_id_format_rejected_detection(self):
        """The old 'al_xxxxxxxxxx' format must not be generated by new code."""
        import src.detection_service as ds
        import inspect
        source = inspect.getsource(ds)
        assert "hex[:10]" not in source, (
            "Truncated UUID hex[:10] still present in detection_service.py"
        )

    def test_save_alert_accepts_full_uuid(self):
        store, path = _make_store()
        try:
            full_id = str(uuid.uuid4())
            store.save_alert(_alert(alert_id=full_id))
            alerts = store.list_alerts(limit=10)
            ids = [a["id"] for a in alerts]
            assert full_id in ids
        finally:
            os.unlink(path)

    def test_save_alert_old_truncated_id_still_accepted(self):
        """Rollback compatibility: old short IDs in existing rows are unaffected."""
        store, path = _make_store()
        try:
            old_id = f"al_{uuid.uuid4().hex[:10]}"
            store.save_alert(_alert(alert_id=old_id))
            alerts = store.list_alerts(limit=10)
            ids = [a["id"] for a in alerts]
            assert old_id in ids
        finally:
            os.unlink(path)


# ---------------------------------------------------------------------------
# D-06-2: Deduplication index exists
# ---------------------------------------------------------------------------

class TestDedupIndexExists:
    def test_uq_alert_dedup_index_exists(self):
        """uq_alert_dedup partial index must exist in sqlite_master."""
        store, path = _make_store()
        try:
            rows = store._fetchall(
                "SELECT name FROM sqlite_master WHERE type='index' AND name='uq_alert_dedup'"
            )
            assert rows, "uq_alert_dedup index not found in sqlite_master"
        finally:
            os.unlink(path)

    def test_dedup_key_column_exists(self):
        """alerts table must have dedup_key column."""
        store, path = _make_store()
        try:
            cols = {row["name"] for row in store._fetchall("PRAGMA table_info(alerts)")}
            assert "dedup_key" in cols, f"dedup_key column missing; found: {cols}"
        finally:
            os.unlink(path)

    def test_schema_version_is_5(self):
        """OpsStore.SCHEMA_VERSION must be 5 after D-06 migration."""
        from src.ops_store import OpsStore
        assert OpsStore.SCHEMA_VERSION == 5


# ---------------------------------------------------------------------------
# D-06-3: ON CONFLICT DO NOTHING deduplication
# ---------------------------------------------------------------------------

class TestAlertDeduplication:
    def test_same_source_attack_window_deduped(self):
        """Two alerts with same source_ip + attack_type in same 5-min window → only 1 stored."""
        store, path = _make_store()
        try:
            ts = datetime(2025, 1, 1, 12, 0, 0, tzinfo=timezone.utc).isoformat()
            store.save_alert(_alert(alert_id=str(uuid.uuid4()), source_ip="1.2.3.4",
                                   attack_type="portscan", timestamp=ts))
            # Same source, attack_type, within same 5-min bucket
            ts2 = datetime(2025, 1, 1, 12, 2, 30, tzinfo=timezone.utc).isoformat()
            store.save_alert(_alert(alert_id=str(uuid.uuid4()), source_ip="1.2.3.4",
                                   attack_type="portscan", timestamp=ts2))
            alerts = store.list_alerts(limit=100)
            count_1234_portscan = sum(
                1 for a in alerts
                if a.get("source_ip") == "1.2.3.4" and a.get("attack_type") == "portscan"
            )
            assert count_1234_portscan == 1, (
                f"Expected 1 alert (deduped), got {count_1234_portscan}"
            )
        finally:
            os.unlink(path)

    def test_different_5min_window_not_deduped(self):
        """Same source + attack_type in different 5-min windows → both stored."""
        store, path = _make_store()
        try:
            ts1 = datetime(2025, 1, 1, 12, 0, 0, tzinfo=timezone.utc).isoformat()
            ts2 = datetime(2025, 1, 1, 12, 5, 0, tzinfo=timezone.utc).isoformat()
            store.save_alert(_alert(alert_id=str(uuid.uuid4()), source_ip="2.3.4.5",
                                   attack_type="bruteforce", timestamp=ts1))
            store.save_alert(_alert(alert_id=str(uuid.uuid4()), source_ip="2.3.4.5",
                                   attack_type="bruteforce", timestamp=ts2))
            alerts = store.list_alerts(limit=100)
            count = sum(
                1 for a in alerts
                if a.get("source_ip") == "2.3.4.5" and a.get("attack_type") == "bruteforce"
            )
            assert count == 2, f"Expected 2 (different windows), got {count}"
        finally:
            os.unlink(path)

    def test_different_attack_type_not_deduped(self):
        """Same source + different attack_type in same window → both stored."""
        store, path = _make_store()
        try:
            ts = datetime(2025, 1, 1, 12, 0, 0, tzinfo=timezone.utc).isoformat()
            store.save_alert(_alert(alert_id=str(uuid.uuid4()), source_ip="3.4.5.6",
                                   attack_type="portscan", timestamp=ts))
            store.save_alert(_alert(alert_id=str(uuid.uuid4()), source_ip="3.4.5.6",
                                   attack_type="bruteforce", timestamp=ts))
            alerts = store.list_alerts(limit=100)
            count = sum(1 for a in alerts if a.get("source_ip") == "3.4.5.6")
            assert count == 2
        finally:
            os.unlink(path)

    def test_different_source_ip_not_deduped(self):
        """Different source_ip with same attack_type + window → both stored."""
        store, path = _make_store()
        try:
            ts = datetime(2025, 1, 1, 12, 0, 0, tzinfo=timezone.utc).isoformat()
            store.save_alert(_alert(alert_id=str(uuid.uuid4()), source_ip="4.5.6.7",
                                   attack_type="ddos", timestamp=ts))
            store.save_alert(_alert(alert_id=str(uuid.uuid4()), source_ip="8.9.10.11",
                                   attack_type="ddos", timestamp=ts))
            alerts = store.list_alerts(limit=100)
            sources = {a.get("source_ip") for a in alerts}
            assert "4.5.6.7" in sources
            assert "8.9.10.11" in sources
        finally:
            os.unlink(path)

    def test_empty_source_ip_not_deduped(self):
        """Alerts with empty source_ip bypass dedup (no dedup_key → NULL)."""
        store, path = _make_store()
        try:
            ts = datetime(2025, 1, 1, 12, 0, 0, tzinfo=timezone.utc).isoformat()
            store.save_alert(_alert(alert_id=str(uuid.uuid4()), source_ip="",
                                   attack_type="unknown", timestamp=ts))
            store.save_alert(_alert(alert_id=str(uuid.uuid4()), source_ip="",
                                   attack_type="unknown", timestamp=ts))
            alerts = store.list_alerts(limit=100)
            count = sum(1 for a in alerts if a.get("source_ip", "") == "")
            assert count == 2, "Empty source_ip alerts must not be deduped"
        finally:
            os.unlink(path)


# ---------------------------------------------------------------------------
# D-06-4: _alert_dedup_key unit tests
# ---------------------------------------------------------------------------

class TestAlertDedupKey:
    def setup_method(self):
        from src.ops_store import OpsStore
        self._fn = OpsStore._alert_dedup_key

    def test_same_inputs_same_key(self):
        ts = "2025-01-01T12:03:00+00:00"
        k1 = self._fn("1.2.3.4", "portscan", ts)
        k2 = self._fn("1.2.3.4", "portscan", ts)
        assert k1 == k2

    def test_different_5min_bucket_different_key(self):
        ts1 = "2025-01-01T12:00:00+00:00"
        ts2 = "2025-01-01T12:05:00+00:00"
        k1 = self._fn("1.2.3.4", "portscan", ts1)
        k2 = self._fn("1.2.3.4", "portscan", ts2)
        assert k1 != k2

    def test_same_5min_bucket_same_key(self):
        ts1 = "2025-01-01T12:00:00+00:00"
        ts2 = "2025-01-01T12:04:59+00:00"
        k1 = self._fn("1.2.3.4", "portscan", ts1)
        k2 = self._fn("1.2.3.4", "portscan", ts2)
        assert k1 == k2

    def test_empty_source_ip_returns_none(self):
        assert self._fn("", "portscan", "2025-01-01T12:00:00+00:00") is None

    def test_different_attack_type_different_key(self):
        ts = "2025-01-01T12:00:00+00:00"
        k1 = self._fn("1.2.3.4", "portscan", ts)
        k2 = self._fn("1.2.3.4", "bruteforce", ts)
        assert k1 != k2
